# Generated by Django 4.2.2 on 2023-06-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_Generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='agent_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='qr',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qr',
            name='generated_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qr',
            name='product_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='qr',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
