# Generated by Django 4.2.2 on 2023-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_Generator', '0002_alter_qr_agent_id_alter_qr_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='agent_id',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qr',
            name='product_id',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
